### ISSUE TITLE
When i want to generate image when" npm run dev"

### ISSUE THREAD

**Issue by TSAIGANESH** [siegblink/interior-designer-ai#22]
⨯ Error: API request failed: Payment Required
    at Replicate.request (webpack-internal:///(rsc)/./node_modules/replicate/index.js:159:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Replicate.createPrediction (webpack-internal:///(rsc)/./node_modules/replicate/lib/predictions.js:38:22)
    at async Replicate.run (webpack-internal:///(rsc)/./node_modules/replicate/index.js:108:24)
    at async POST (webpack-internal:///(rsc)/./app/api/replicate/route.ts:29:20)
    at async C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57228 
    at async eT.execute (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46851)
    at async eT.handle (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:58562)
    at async doRender (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\base-server.js:1353:42)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\base-server.js:1575:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\base-server.js:1483:28)
    at async DevServer.renderPageComponent (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\base-server.js:1911:24)
    at async DevServer.renderToResponseImpl (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\base-server.js:1949:32)
    at async DevServer.pipeImpl (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\base-server.js:921:25)     
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\base-server.js:817:17)
    at async C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\lib\router-server.js:173:21)     
    at async handleRequest (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\lib\router-server.js:350:24)    
    at async requestHandlerImpl (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\Users\sai ganesh\interior-designer-ai\node_modules\next\dist\server\lib\start-server.js:141:13)
 POST /api/replicate 500 in 2744ms

**Comment by manvithasp** [comment]
You need to add your payment information at the replicate website to continue using the API key and generate images

**Comment by menyunlei** [comment]
> You need to add your payment information at the replicate website to continue using the API key and generate images

Can we use local model?
